services: docker

env:
    - distro: williamyeh/ansible:debian8
    - distro: williamyeh/ansible:debian7
    - distro: williamyeh/ansible:ubuntu16.04
    - distro: williamyeh/ansible:ubuntu14.04
    - distro: williamyeh/ansible:ubuntu12.04
    - distro: williamyeh/ansible:centos7
    - distro: williamyeh/ansible:centos6

before_install:
    - docker pull "${distro}"
    
script:
    
    - role_path=/etc/ansible/roles/DNS-Bind9
    
    - conf_hostname=yoda
    
    - conf_domain=jedi
    
    - master_id="$(docker run -d -v $(pwd):${role_path}:ro ${distro} tail -f /dev/null)" || exit 1
    
    - slave_id="$(docker run -d -v $(pwd):${role_path}:ro ${distro} tail -f /dev/null)" || exit 1
    
    - master_ip="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${master_id})" || exit 1
    
    - slave_ip="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${slave_id})" || exit 1
    
    - docker exec "${master_id}" /bin/bash $role_path/tests/test_master.sh "${role_path}" "${master_ip}"  "${slave_ip}" "${conf_hostname}" "${conf_domain}" || exit 1
    
    - docker exec "${slave_id}" /bin/bash $role_path/tests/test_slave.sh "${role_path}" "${master_ip}" "${slave_ip}" "${conf_hostname}" "${conf_domain}" || exit 1
    
    - docker exec "${master_id}" service bind9 stop || exit 1
    
    - docker exec "${slave_id}" ping -c 4 "${conf_hostname}"."${conf_domain}" || exit 1
