services: docker

env:
    - distro: mrlarbi/ansible:debian8
      command: tail -f /dev/null
      run_options: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distro: mrlarbi/ansible:debian7
      command: tail -f /dev/null
      run_options: ""
    - distro: mrlarbi/ansible:ubuntu16.04
      command: tail -f /dev/null
      run_options: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distro: mrlarbi/ansible:ubuntu14.04
      command: tail -f /dev/null
      run_options: ""
    - distro: mrlarbi/ansible:ubuntu12.04
      command: tail -f /dev/null
      run_options: ""
    - distro: mrlarbi/ansible:centos7
      command: /usr/lib/systemd/systemd
      run_options: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distro: mrlarbi/ansible:centos6
      command: tail -f /dev/null
      run_options: ""

before_install:
    - docker pull "${distro}"
    
script:
    
    - role_path=/etc/ansible/roles/DNS-Bind9
    
    - conf_hostname=yoda
    
    - conf_domain=jedi
    
    - master_id="$(docker run -d ${run_options} -v $(pwd):${role_path}:ro ${distro} ${command})" || exit 1
    
    - slave_id="$(docker run -d ${run_options} -v $(pwd):${role_path}:ro ${distro} ${command})" || exit 1
    
    - master_ip="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${master_id})" || exit 1
    
    - slave_ip="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${slave_id})" || exit 1
    
    - docker exec "${master_id}" /bin/bash $role_path/tests/test_master.sh "${role_path}" "${master_ip}"  "${slave_ip}" "${conf_hostname}" "${conf_domain}" || exit 1
    
    - docker exec "${slave_id}" /bin/bash $role_path/tests/test_slave.sh "${role_path}" "${master_ip}" "${slave_ip}" "${conf_hostname}" "${conf_domain}" || exit 1
    
    - docker exec "${master_id}" service bind9 stop \
      || docker exec "${master_id}" service named stop \
      || docker exec "${master_id}" systemctl stop named \
      || docker exec "${master_id}" systemctl stop bind9 \
      || exit 1
    
    - docker exec "${slave_id}" ping -c 4 "${conf_hostname}"."${conf_domain}" || exit 1
