services: docker

env:
    - distro: debian:jessie

before_install:
    - docker pull williamyeh/ansible:debian8
    
script:
    
    - role_path=/etc/ansible/roles/DNS-Bind9
    
    - docker run -d -v "$(pwd)":"$role_path":ro williamyeh/ansible:debian8 ansible-playbook --version
