services: docker

env:
    - distro: debian:jessie

before_install:
    - docker pull williamyeh/ansible:debian8
    
script:
    
    - role_path=/etc/ansible/roles/DNS-Bind9
    
    - docker run -v "$(pwd)":"$role_path":ro williamyeh/ansible:debian8 $role_path/tests/test.sh $role_path
    
    - 
