services: docker

env:
    - distro: williamyeh/ansible:debian8

before_install:
    - docker pull "${distro}"
    
script:
    
    - role_path=/etc/ansible/roles/DNS-Bind9
    
    - master_id="$(docker run -d -v $(pwd):${role_path}:ro ${distro} tail -f /dev/null)"
    
    - slave_id="$(docker run -d -v $(pwd):${role_path}:ro ${distro} tail -f /dev/null)"
    
    - master_ip="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${master_id})"
    
    - slave_ip="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${slave_id})"
    
    - docker exec "${master_id}" /bin/bash $role_path/tests/test_master.sh "${role_path}"
    
    - docker exec "${slave_id}" /bin/bash $role_path/tests/test_slave.sh "${role_path}"
