- name: Install the latest version of bind9 for Debian
  apt:
      name=bind9
      state=latest
  when: ansible_os_family == "Debian"
  
- name: Install the latest version of bind9 for RedHat
  yum:
      name="bind,bind-utils"
      state=latest
  when: ansible_os_family == "RedHat"
  
- name: Install the latest version of bind9 for ArchLinux
  pacman:
      name=bind9
      state=latest
  when: ansible_os_family == "ArchLinux"

- name: Ensure the directory {{ bind_path }} is present
  file:
      path="{{ bind_path }}"
      state=directory
      mode=0755
      owner="{{ bind_user }}"
      group="{{ bind_user }}"

- name: Ensure the file {{ bind_path }}/named.conf.options is present
  file:
      path="{{ bind_path }}/named.conf.options"
      state=touch
      mode=0755
      owner="{{ bind_user }}"
      group="{{ bind_user }}"

- name: Ensure the directory /var/cache/bind is present
  file:
      path=/var/cache/bind
      state=directory
      mode=775
      owner="{{ bind_user }}"
      group="{{ bind_user }}"

- name: Configure the {{ bind_named_conf_path }}
  template:
      src=named.j2
      dest="{{ bind_named_conf_path }}"
      owner="{{ bind_user }}"
      group="{{ bind_user }}"
