- include_vars: main_vars.yml

- include_vars: "{{ ansible_os_family }}_vars.yml"

- name: Install Bind9
  include: install_bind9.yml

- name: Set needed facts
  include: set_facts.yml

- name: Configure DNS Cache
  include: configure_cache.yml
  when: is_cache == True
  
- name: Configure DNS Master
  include: configure_master.yml
  when: is_master == True

- name: Configure DNS Slave
  include: configure_slave.yml
  when: is_master == False and is_slave == True
  
- name: Ensure bind9 is started and enabled at boot
  service: 
    name=bind9
    state=restarted
    enabled=yes
