- name: Set hostname
  set_fact:
      bind_hostname: "{{ ansible_hostname }}"
  when: bind_hostname == ""
  failed_when: domain_name == ""
  
- name: Set domain_name
  set_fact:
      bind_domain_name: "{{ ansible_domain }}"
  when: bind_domain_name == ""
  failed_when: domain_name == ""
  
- name: Set ip
  set_fact:
      bind_ip: "{{ ansible_all_ipv4_addresses[0] }}"
  when: bind_ip == ""
  failed_when: bind_ip == ""

- name: Set fqdn
  set_fact:
      fqdn: "{{ bind_hostname }}.{{ bind_domain_name }}"

- name: Set mail
  set_fact:
      bind_mail: "{{ ansible_user_id }}.{{ bind_domain_name }}"
  when: bind_mail == ""

- name: Set reverse ip
  set_fact:
      reverse_ip: "{{ bind_ip.split('.')[2] }}.{{ bind_ip.split('.')[1] }}.{{ bind_ip.split('.')[0] }}"

- name: Set last ip byte
  set_fact:
      first_ip_byte: "{{ bind_ip.split('.')[0] }}"
      
- name: Set last ip byte
  set_fact:
      last_ip_byte: "{{ bind_ip.split('.')[3] }}"
